# site settings
title: LENDER DANASYARIAH
subtitle: by PAGUYUBAN
email: paguyuban.lenderdsi@gmail.com
description: Portal ini dikelola oleh Tim Paguyuban Lender DSI sebagai pusat informasi dan komunikasi yang menjembatani para lender dengan pihak PT Dana Syariah Indonesia (DSI). Melalui portal ini, Paguyuban berperan sebagai wadah kolaborasi dan koordinasi untuk menyampaikan informasi terkini, menampung aspirasi lender, serta memperkuat transparansi penyelesaian issue yang terjadi di danasyariah.id
baseurl:
url: "https://danasyariah.github.io"
author: "Paguyuban Lender DanaSyariah.id"
street_address: AD PREMIER 17th Flor suite 04 B, Jl. TB Simatupang No.5, RT.5/RW.7, Ragunan, Ps. Minggu
city: Kota Jakarta Selatan
state: Daerah Khusus Ibukota Jakarta
zip_code: 12550
country: Indonesia
phone: +6285121319859

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://instagram.com/dsi.lender
  LinkedIn: 
  Twitter: https://twitter.com/danasyariah_id
  Facebook:
  Slack:
  Telegram: https://t.me/+bqCLOOZk9sJjYjVl

# build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
